export enum InventoryTypeFilterEnum {
    Any = 'any',
    Sittable = 'sittable',
    Layable = 'layable',
    TilesOrRugs = 'tiles_or_rugs',
    Ltd = 'ltd',
    Wired = 'wired',
    CreditFurni = 'credit_furni',
    Clothes = 'clothes',
    PetFood = 'pet_food',
    Collectibles = 'collectibles',
    Tradable = 'tradable',
    NonTradable = 'non_tradable',
    Recyclable = 'recyclable',
    Windows = 'windows',
    Dimmers = 'dimmers',
    Stickies = 'stickies',
    Paintings = 'paintings',
    Floors = 'floors',
    Wallpapers = 'wallpapers',
    Landscape = 'landscape'
}
